### ISSUE TITLE
Update telephone number pattern

### ISSUE THREAD

**Issue by adamlocker** [FoodStandardsAgency/enterprise-data-models#10]
- Simplify for FSA use cases
- Link out to gov.uk pattern and notify docs
- Reduce background info

**Comment by Jamie-Atkinson** [comment]
notify documentation: https://docs.notifications.service.gov.uk/
Design pattern: https://design-system.service.gov.uk/patterns/telephone-numbers/

**Comment by pc42** [comment]
Further changes made following review

**Comment by pc42** [comment]
AL reviewed happy to move to baselined at v1.0
