### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by Jamie-Atkinson** [FoodStandardsAgency/enterprise-data-models#11]

**Comment by adamlocker** [comment]
Had some inspiration whilst chipping a metric ton of bamboo in my garden Saturday.

The parent entity is `Action`, the child entities are `Activity`, `Intervention`, and `Enforcement`.

**Comment by JDSFSA** [comment]
I started Management under controlled scheme last week, this could be renamed as action as I believe it  sits and fulfills a similar role?
