### ISSUE TITLE
approval for the start-date, end-date and change-date entity models

### ISSUE THREAD

**Issue by Jamie-Atkinson** [FoodStandardsAgency/enterprise-data-models#4]
Would apreciate some input as to whether people are happy with the start-date, end-date and change-date entity models and if they are ready to move to current.

files in question:
[change-date](https://github.com/FoodStandardsAgency/enterprise-data-models/blob/master/model/draft/change-date.md) [end-date](https://github.com/FoodStandardsAgency/enterprise-data-models/blob/master/model/draft/end-date.md) [start-date](https://github.com/FoodStandardsAgency/enterprise-data-models/blob/master/model/draft/start-date.md)

**Comment by adamlocker** [comment]
Going to close this after recent discussions and split into patterns and entities.
