### ISSUE TITLE
Audit

### ISSUE THREAD

**Issue by JDSFSA** [FoodStandardsAgency/enterprise-data-models#49]

**Comment by JDSFSA** [comment]
Audit entity created and diagram attached waiting on review

**Comment by adamlocker** [comment]
I have reviewed this and while the content is fine I am not sure that the entity needs to exist at all at this time.

As far as I can tell, there are not generic properties of audit that aren't expressed as part of the inspection entity and audit is simply a synonym. As it stands the majority of the content in the entity is just background.

We will leave this entity in drafts until further notice.
