### ISSUE TITLE
Competent Authority Updates

### ISSUE THREAD

**Issue by adamlocker** [FoodStandardsAgency/enterprise-data-models#80]
These are comments based on the current entity published entity. They may appear in other entities as well.

- [x] Entity diagram cardinality relationships are inconsistent across entities, this one uses crow's feet.
- [x] Diagram could be a little larger. We need to develop some standard templating for them.
- [x] External references section needs tidying.

**Comment by pc42** [comment]
Have removed External references section.  We will need to add guidance re extracting CA information from Data Lake when established and also make reference to procedures for updating CAs when established
