### ISSUE TITLE
Enforcement Updates

### ISSUE THREAD

**Issue by adamlocker** [FoodStandardsAgency/enterprise-data-models#81]
These are comments based on the current entity published entity. They may appear in other entities as well.

- [x] The diagram here needs updating in line with the comments made for improvements to the Activity Entity #78 
- [ ] Some of the language needs cleaning up and proof-reading.
- [x] Add additional info to contextual properties, currently it says;
   > "By recording the reason for the Enforcement actions it gives Competent Authorities the ability to look for trends and focus on areas for further interventions, or build a case for stronger enforcement."

This is likely to close to an opinion. We may wish to be more general and say that as far as data is concerned, when recording the reason for enforcement, we prefer to use a controlled vocabulary of reasons to make analysis easier.

**Comment by JDSFSA** [comment]
1 - Diagram updated
2 - re-read entity
3 - updated contextual properties section

**Comment by JDSFSA** [comment]
update diagram triple version
update to stable, version number
