### ISSUE TITLE
Intervention Updates

### ISSUE THREAD

**Issue by adamlocker** [FoodStandardsAgency/enterprise-data-models#82]
These are comments based on the current entity published entity. They may appear in other entities as well.

- [x] Diagram to be updated in line with activity and enforcement entities
- [x] Contextual properties are inconsistent with earlier definition. It says the name of the establishment it was applied to but earlier in the entry it says that interventions can be applied to establishments, premises, operators or a person. It should say that you should "record the identifier of the entity that the intervention is applied to" to make it more generic.
- [x] Header for "Contextual Properties" is incorrect.

**Comment by JDSFSA** [comment]
1 - Diagram updated
2 - updated contextual properties section
3 - updated contextual properties header

**Comment by JDSFSA** [comment]
update diagram
missing links for person
update to stable, version number
