### ISSUE TITLE
Operator Updates

### ISSUE THREAD

**Issue by adamlocker** [FoodStandardsAgency/enterprise-data-models#83]
These are comments based on the current entity published entity. They may appear in other entities as well.

- [x] A linked entry for `contact` is missing. Might consider making this a pattern.
- [x] Diagram has the CA sponsoring the scheme but not sure that is correct.
- [x] This diagram apprears to be more UML style as it has arrows, we really need to sort these out 😂 
- [x] Link to plant approval number and address patterns missing.
- [x] Need a Charity Commission number pattern (maybe create an issue for this).

**Comment by pc42** [comment]
issue #89 created for Charity Commission Number
