### ISSUE TITLE
Scheme Updates

### ISSUE THREAD

**Issue by adamlocker** [FoodStandardsAgency/enterprise-data-models#85]
These are comments based on the current entity published entity. They may appear in other entities as well.

- [x] This diagram has nice round corners, well 2 of the 3 corners are. Need to be consistent with our diagrams I think.
- [x] I think we need to make clearer the differences between owning, managing and carrying out a scheme. I reckon the second one may be redundant.
- [x] Comma after "for example" in "for example FHRS is owned...."
- [x] We need to actually make a register of schemes that meet our model. FHRS and approved establishments so far.
- [x] I am not sure the RCDM policy is a scheme, is it?

**Comment by JDSFSA** [comment]
1 - Diagram updated, 
2 - changed to Owns or administers a scheme
3 - comma added
4 - list of schemes  https://foodgov.sharepoint.com/sites/data/Lists/Schemes/AllItems.aspx 
5 - I think it fits in with our definition and there are tighter controls, but I've removed it from the External references and further reading section

**Comment by JDSFSA** [comment]
Need to make stable and update date and version number.
