### ISSUE TITLE
Charity Commission Number

### ISSUE THREAD

**Issue by pc42** [FoodStandardsAgency/enterprise-data-models#89]
Haven't been ale to find any definitive format for a Charitable Commission Number, other than when looking at the register the numbers would appear to start at 6 numerical digits rising to 7 numerical digits for recent registrations - website link - 
https://www.gov.uk/government/organisations/charity-commission/about/publication-scheme

The website does mention future development of an api whereby it may be possible to link to a specific charity on the Charity Commission register

Per Operator the number is used in the same context as Company number, if this is the case and a charity number is recorded against the Company number an alternative could be to expand the Companies House number pattern to incorporate, and review periodically to check for changes

- [ ] add link to operator page

**Comment by pc42** [comment]
@JDSFSA - if you think the above is a reasonable option I'll amend the Companies House Number Pattern

**Comment by JDSFSA** [comment]
I may have miss read what your suggesting but I don't think we should use the charity number as the company number, personally I think these should be in separate fields.

As for the pattern of the charity number could we say something like we follow the number format compiled by the Charity commission register, and that is currently either a 6 or 7 character string but this may change?  Its not something we have control of just something we use and need to work within their parameters.

**Comment by pc42** [comment]
Charity commission number created
